backend:
  name: github
  repo: swartists/starworksartists.com
  branch: development # Branch to update (optional; defaults to master)

#display_url: https://example.com
#media_folder: "assets/uploads"

media_folder: 'static/img' # this is where netlify cms places images.
public_folder: '/img' # this is where gatsby places images

collections: # A list of collections the CMS should be able to edit

  - name: artists
    label: Artists
    folder: 'src/pages/artists'
    slug: '/artists/{{slug}}'
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {name: kind, widget: hidden, default: 'artist'}
      - {label: "Name", name: "title", widget: "string", tagname: "h1"}
      - {label: "Type", name: "type", widget: "select", options: ["hair", "makeup", "stylist", "grooming", "manicurist", "special-bookings"]}
      - {label: "Cover Image", name: "cover", widget: "image",
      required: false, tagname: ""}
      - {label: "Instagram handle", name: "instagram_handle", widget: "string", tagname: "p", required: false}
      - {label: "Enquire", name: "enquire", widget: "string", tagname: "p", required: false}
      - name: portfolios
        label: Portfolios
        widget: list
        required: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - name: gallery
            label: Gallery
            widget: gallery
            required: false
            fields:
              - {name: image, label: Image, widget: image, class: 'gallery'}
      - name: videos
        label: Videos
        widget: vimeo
        required: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'ID', name: 'url', widget: 'number'}
          - {label: 'Ratio', name: 'ratio', widget: 'string'}
          - {label: 'Poster', name: 'poster', widget: 'string'}
      - {label: "Biography Text", name: "body", widget: "markdown", required: false}

  - name: services
    label: Services
    folder: 'src/pages/services'
    slug: '/services/{{slug}}'
    create: true
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
    fields:
      - {label: "Order", name: "order", widget: "number", min: 1, max: 99}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Description", name: "description", widget: "text"}
      - label: Bullets
        label_singular: Bullet
        name: bullets
        widget: list
        required: false
        fields:
          - {label: Bullet, name: text, widget: string}


  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: metadata
        label: Global Settings
        file: data/site-metadata.yml
        description: "Settings"
        fields:
          - {label: "Name of website", name: title, widget: "string"}
          - {label: "Google Analytics UA-Code", name: trackingId, widget: "string"}
          - label: "Meta"
            name: meta
            widget: object
            fields:
              - label: Description
                name: description
                widget: text
                required: false
              - label: Keywords
                name: keywords
                widget: text
                required: false

      - name: agency
        label: Agency
        file: 'data/agency.yml'
        fields:
          - {label: "Title", name: "title", widget: "string", tagname: "h1"}
          - {label: "Description", name: "description", widget: "text"}
          - name: contact
            label: Contact
            widget: list
            required: false
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Name, name: name, widget: string}
              - {label: Url, name: url, widget: string}
          - name: addresses
            label: Addresses
            widget: list
            required: false
            fields:
              - {label: Header, name: header, widget: string}
              - {label: Address, name: address, widget: text}



  - name: "kitchenSink" # all the things in one entry, for documentation and quick testing
    label: "Kitchen Sink"
    folder: "_sink"
    create: true
    fields:
      - label: "Related Post"
        name: "post"
        widget: "relationKitchenSinkPost"
        collection: "posts"
        searchFields: ["title", "body"]
        valueField: "title"
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Boolean", name: "boolean", widget: "boolean", default: true}
      - {label: "Text", name: "text", widget: "text"}
      - {label: "Number", name: "number", widget: "number"}
      - {label: "Markdown", name: "markdown", widget: "markdown"}
      - {label: "Datetime", name: "datetime", widget: "datetime"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "File", name: "file", widget: "file"}
      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
      - label: "Object"
        name: "object"
        widget: "object"
        fields:
          - label: "Related Post"
            name: "post"
            widget: "relationKitchenSinkPost"
            collection: "posts"
            searchFields: ["title", "body"]
            valueField: "title"
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean", default: false}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "String", name: "string", widget: "string"}
          - {label: "Boolean", name: "boolean", widget: "boolean"}
          - {label: "Text", name: "text", widget: "text"}
          - {label: "Number", name: "number", widget: "number"}
          - {label: "Markdown", name: "markdown", widget: "markdown"}
          - {label: "Datetime", name: "datetime", widget: "datetime"}
          - {label: "Date", name: "date", widget: "date"}
          - {label: "Image", name: "image", widget: "image"}
          - {label: "File", name: "file", widget: "file"}
          - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
          - label: "Object"
            name: "object"
            widget: "object"
            fields:
              - {label: "String", name: "string", widget: "string"}
              - {label: "Boolean", name: "boolean", widget: "boolean"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Number", name: "number", widget: "number"}
              - {label: "Markdown", name: "markdown", widget: "markdown"}
              - {label: "Datetime", name: "datetime", widget: "datetime"}
              - {label: "Date", name: "date", widget: "date"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "File", name: "file", widget: "file"}
              - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
              - label: "List"
                name: "list"
                widget: "list"
                fields:
                  - label: "Related Post"
                    name: "post"
                    widget: "relationKitchenSinkPost"
                    collection: "posts"
                    searchFields: ["title", "body"]
                    valueField: "title"
                  - {label: "String", name: "string", widget: "string"}
                  - {label: "Boolean", name: "boolean", widget: "boolean"}
                  - {label: "Text", name: "text", widget: "text"}
                  - {label: "Number", name: "number", widget: "number"}
                  - {label: "Markdown", name: "markdown", widget: "markdown"}
                  - {label: "Datetime", name: "datetime", widget: "datetime"}
                  - {label: "Date", name: "date", widget: "date"}
                  - {label: "Image", name: "image", widget: "image"}
                  - {label: "File", name: "file", widget: "file"}
                  - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
                  - {label: "Hidden", name: "hidden", widget: "hidden", default: "hidden"}
                  - label: "Object"
                    name: "object"
                    widget: "object"
                    fields:
                      - {label: "String", name: "string", widget: "string"}
                      - {label: "Boolean", name: "boolean", widget: "boolean"}
                      - {label: "Text", name: "text", widget: "text"}
                      - {label: "Number", name: "number", widget: "number"}
                      - {label: "Markdown", name: "markdown", widget: "markdown"}
                      - {label: "Datetime", name: "datetime", widget: "datetime"}
                      - {label: "Date", name: "date", widget: "date"}
                      - {label: "Image", name: "image", widget: "image"}
                      - {label: "File", name: "file", widget: "file"}
                      - {label: "Select", name: "select", widget: "select", options: ["a", "b", "c"]}
