backend:
  name: github
  repo: owenhoskins/netlify-cms-gallery
  branch: uploadcare # Branch to update (optional; defaults to master)

display_url: https://example.com

# publish_mode: editorial_workflow
media_folder: assets/uploads
media_library:
  name: uploadcare
  config:
    #publicKey: demopublickey
    publicKey: 50f112d73966e78a7993

collections: # A list of collections the CMS should be able to edit
  - name: "page"
    label: "Page"
    folder: "src/pages/gallery"
    slug: "/gallery/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - label: "Cover Image"
        name: "image"
        widget: "image"
      - name: portfolios
        label: Portfolios
        widget: list
        required: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - name: "gallery"
            label: "Gallery"
            widget: "gallery"
            class: "gallery"
            allow_multiple: true
            options:
              media_library:
                config:
                  multiple: true
