backend:
  name: github
  repo: owenhoskins/netlify-cms-gallery
  branch: uploadcare # Branch to update (optional; defaults to master)

display_url: https://example.com

# publish_mode: editorial_workflow
media_folder: assets/uploads
media_library:
  name: uploadcare
  config:
    #publicKey: demopublickey
    publicKey: 50f112d73966e78a7993

collections: # A list of collections the CMS should be able to edit
  - name: "page"
    label: "Page"
    folder: "src/pages/gallery"
    slug: "/gallery/{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", tagname: "h1" }
      - label: "Cover Image"
        name: "image"
        widget: "image"
        options:
          media_library:
            config:
              multiple: false
      - name: portfolios
        label: Images
        label_singular: Portfolio
        widget: list
        required: false
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - name: "gallery"
            label: "Gallery"
            widget: "gallery"
            class: "gallery"
      - name: videos
        label: Videos
        label_singular: Video
        widget: vimeo
        required: false
        fields:
          - {label: 'ID', name: 'url', widget: 'number', valueType: 'int'}
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Poster', name: 'poster', widget: 'string'}
          - {label: 'Ratio', name: 'ratio', widget: 'string'}
